apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
        - image: localhost:5000/subscriber:dev
          imagePullPolicy: Always
          name: subscriber
          ports:
            - name: http
              containerPort: 8080
            - name: prometheus
              containerPort: 9090
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker