apiVersion: v1
kind: Service
metadata:
  labels:
    name: subscriber
  name: subscriber
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: http
    - protocol: TCP
      name: prometheus
      port: 9090
      targetPort: prometheus
  selector:
    app: subscriber