@events.publisher_HostAddress = http://localhost:8180
@events.prometheus_HostAddress = http://localhost:9190

POST {{events.publisher_HostAddress}}/api/Publish
Content-Type: application/json

[
  {
    "data": {
      "year": 2017,
      "month": 1,
      "day": 3,
      "appointment": "clinic",
      "email": "{{$random.email}}"
    },
    "name": "test.event",
    "id": "1",
    "group": "1"
  }
]

###

GET {{events.prometheus_HostAddress}}/internal/metrics

###