@events.management_HostAddress = http://localhost:5100

POST {{events.management_HostAddress}}/api/Events
Accept: application/json
Content-Type: application/json

[
  {
    "name": "test.abc.firdaus",
    "id": "string",
    "group": "string",
    "destination": {
      "$type" : "webhook",
      "url": "https://www.google.com",
      "contentType": "https://www.google.com"
    }
  }
]

###
